### ISSUE TITLE
Installation fails on `psr/log-implementation` being a 'Virtual Package'

### ISSUE THREAD

**Issue by mediact-pipelines** [HipexBV/PackApi#4]
When following instructions on installing the package you will get the following error:
```
% composer require hipex/pack-api

Using version ^1.38 for hipex/pack-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for hipex/pack-api ^1.38 -> satisfiable by hipex/pack-api[v1.38.0].
    - hipex/pack-api v1.38.0 requires psr/log-implementation ^1.0 -> no matching package found.
```
Packagist learns me that `psr/log-implementation` is a 'Virtual package' that can not be installed by itself
https://packagist.org/packages/hipex/pack-api?query=psr%2Flog-implementation

Instead you have to require one of the following packages
https://packagist.org/providers/psr/log-implementation

So I for now I worked around the issue by requiring `monolog/monolog`

**Comment by Fgruntjes** [comment]
Hello,

Thank you for your issue report. You are right, the package requires at least an implementation of any of the https://packagist.org/providers/psr/log-implementation.

Magento 2 by default already requires `monolog/monolog`, so no real problem there. For Magento 1 we will update the readme.
